server:
  port: 8000

spring:
  application:
    name: apigateway
  cloud:
    gateway:
      routes:
        - id: todo-app
          uri: lb://TODO-APP
          predicates:
            - Path=/todo-app/**

        - id: temp-server
          uri: lb://TEMP-SERVER
          predicates:
            - Path=/temp-server/**


eureka:
  instance:
    instance-id: ${spring.cloud.client.hostname}:${spring.application.instance_id:${random.value}}
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
