server:
  port: 0

spring:
  application:
    name: temp-server

  # H2 Database ??
  datasource:
    driver-class-name: org.h2.Driver
    url: 'jdbc:h2:mem:test'

  # H2 Console ??
  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    database: postgresql
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  logging:
    level:
      org:
        hibernate:
          type:
            descriptor:
              sql: trace

eureka:
  instance:
    instance-id: ${spring.cloud.client.hostname}:${spring.application.instance_id:${random.value}}
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/