server:
  port: 0

spring:
  application:
    name: todo-app
#  datasource:
#    url: jdbc:postgresql://localhost:5432/testDB
#    username: ${DB_USER}
#    password: ${DB_PASSWORD}
#    driver-class-name: org.postgresql.Driver

  # H2 Database 설정
  datasource:
    driver-class-name: org.h2.Driver
    url: 'jdbc:h2:mem:test'
    #url: 'jdbc:h2:~/test'

  # H2 Console 설정
  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    database: postgresql
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace

eureka:
  instance:
    instance-id: ${spring.cloud.client.hostname}:${spring.application.instance_id:${random.value}}
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/